spring:
  datasource:
    username: root
    password: abc123
    url: jdbc:mysql://localhost:3306/article_collect?ServerTimezone=GMT%2B8
  output:
    ansi:
      enabled: detect
  elasticsearch:
    rest:
      uris: 192.168.12.128:9200





